<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="GlobalExceptionHandler\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\DTOs\DTOs.csproj" />
    <ProjectReference Include="..\..\Shared\Entities\Entities.csproj" />
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\FileRepositories\FileRepositories.csproj" />
    <ProjectReference Include="..\RepositoryContracts\RepositoryContracts.csproj" />
  </ItemGroup>

</Project>
